name: Render diagram preview

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: |
            go.mod
            go.sum

      - name: Download dependencies
        run: go mod download

      - name: Build Nagare server
        run: go build -o nagare-server ./cmd

      - name: Start Nagare server
        run: |
          ./nagare-server > server.log 2>&1 &
          echo $! > server.pid

      - name: Render regression diagrams via /render
        run: |
          set -euo pipefail

          shopt -s nullglob
          diagrams=(.github/testdiagrams/*.nagare)
          if [ ${#diagrams[@]} -eq 0 ]; then
            echo "No .nagare files found in .github/testdiagrams" >&2
            exit 1
          fi

          # Wait for the server to be ready.
          for attempt in {1..60}; do
            if curl -fsS http://localhost:8080/test >/dev/null 2>&1; then
              break
            fi
            if [ "$attempt" -eq 60 ]; then
              echo "Server failed to respond" >&2
              exit 1
            fi
            sleep 1
          done

          for nagare_file in "${diagrams[@]}"; do
            base_name=$(basename "$nagare_file" .nagare)
            echo "Rendering $nagare_file"
            curl -fsS -X POST \
              -H 'Content-Type: text/plain' \
              --data-binary @"$nagare_file" \
              http://localhost:8080/render \
              -o "${base_name}.svg"
          done

      - name: Stop Nagare server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
            sleep 1
            if kill -0 $(cat server.pid) 2>/dev/null; then
              kill -9 $(cat server.pid) 2>/dev/null || true
            fi
          fi
          echo '--- Nagare server log ---'
          cat server.log || true

      - name: Upload SVGs to repository and create PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          SERVER_URL: ${{ github.server_url }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          set -euo pipefail

          if [ "$PR_REPO" != "$REPO" ]; then
            echo "Skipping SVG upload because PR comes from a fork"
            exit 0
          fi

          mkdir -p .github/pr-images/pr-$PR_NUMBER

          if ! cp ./*.svg .github/pr-images/pr-$PR_NUMBER/ 2>/dev/null; then
            echo "No SVG files found to upload"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD)}"
          git fetch origin "$BRANCH_NAME"
          git checkout -B "$BRANCH_NAME" "origin/$BRANCH_NAME"

          git add .github/pr-images/pr-$PR_NUMBER/
          if git diff --cached --quiet; then
            echo "No SVG updates to commit"
            exit 0
          fi

          git commit -m "Add generated SVG examples for PR #$PR_NUMBER [skip ci]"

          if ! git push origin "$BRANCH_NAME"; then
            echo "Push failed; attempting to rebase onto latest remote" >&2
            git fetch origin "$BRANCH_NAME"
            git pull --rebase origin "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
          fi

          CURRENT_SHA=$(git rev-parse HEAD)
          HEAD_HTML="$SERVER_URL/$REPO/commit/$CURRENT_SHA"

          COMMENT_BODY="## 🎨 Generated SVG Examples\n\n"

          shopt -s nullglob
          diagrams=(.github/testdiagrams/*.nagare)
          if [ ${#diagrams[@]} -eq 0 ]; then
            echo "No diagrams found to document" >&2
            exit 0
          fi

          for nagare_file in "${diagrams[@]}"; do
            nagare_name=$(basename "$nagare_file")
            base_name=${nagare_name%.nagare}
            filename="${base_name}.svg"
            svg_file=.github/pr-images/pr-$PR_NUMBER/$filename

            if [ ! -f "$svg_file" ]; then
              echo "Skipping $nagare_name because $svg_file is missing" >&2
              continue
            fi

            raw_url="https://github.com/$REPO/blob/$CURRENT_SHA/.github/pr-images/pr-$PR_NUMBER/$filename?raw=1"
            nagare_url="https://github.com/$REPO/blob/$CURRENT_SHA/.github/testdiagrams/$nagare_name"

            COMMENT_BODY+="### ${nagare_name}\n"
            COMMENT_BODY+="![${nagare_name}](${raw_url})\n\n"
            COMMENT_BODY+="<details><summary>View sources</summary>\n\n"
            COMMENT_BODY+=$(printf '[`%s`](%s) · [`%s`](%s)\n\n' "$filename" "$raw_url" "$nagare_name" "$nagare_url")
            COMMENT_BODY+="</details>\n\n"
          done

          COMMENT_BODY+="---\n"
          COMMENT_BODY+="*Generated from commit: [\`$CURRENT_SHA\`]($HEAD_HTML)*\n"
          COMMENT_BODY+="*Workflow run: [\`$RUN_ID\`]($SERVER_URL/$REPO/actions/runs/$RUN_ID)*\n"
          COMMENT_BODY+="*Images stored in: \`.github/pr-images/pr-$PR_NUMBER/\`*"

          printf '%b' "$COMMENT_BODY" > comment.md

          gh pr comment "$PR_NUMBER" --body-file comment.md

          echo "✅ SVG files uploaded and PR comment created successfully"

      - name: Clean up old PR image directories (optional)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail

          if [ "$PR_REPO" != "$REPO" ]; then
            echo "Skipping cleanup for forked PR"
            exit 0
          fi

          BRANCH_NAME="${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD)}"
          git fetch origin "$BRANCH_NAME"
          git checkout -B "$BRANCH_NAME" "origin/$BRANCH_NAME"

          for dir in .github/pr-images/pr-*; do
            if [ -d "$dir" ]; then
              pr_num=$(basename "$dir" | sed 's/pr-//')
              if ! gh pr view "$pr_num" >/dev/null 2>&1; then
                echo "Cleaning up images for closed PR #$pr_num"
                git rm -rf "$dir"
              fi
            fi
          done

          if ! git diff --cached --quiet 2>/dev/null; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Clean up images for closed PRs [skip ci]"
            git push origin "$BRANCH_NAME"
          fi
        continue-on-error: true
