name: Render diagram preview

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: true
          cache-dependency-path: |
            nagare/go.mod
            nagare/go.sum

      - name: Download dependencies
        working-directory: nagare
        run: go mod download

      - name: Build Nagare server
        working-directory: nagare
        run: go build -o nagare-server ./cmd/nagare

      - name: Start Nagare server
        run: |
          cd nagare
          ./nagare-server > server.log 2>&1 &
          echo $! > server.pid

      - name: Fetch /test SVG output
        run: |
          for attempt in {1..60}; do
            if curl -fsS http://localhost:8080/test -o nagare-test.svg; then
              exit 0
            fi
            sleep 1
          done
          echo "Server failed to respond" >&2
          exit 1

      - name: Stop Nagare server
        if: always()
        run: |
          if [ -f nagare/server.pid ]; then
            kill $(cat nagare/server.pid) 2>/dev/null || true
            sleep 1
            if kill -0 $(cat nagare/server.pid) 2>/dev/null; then
              kill -9 $(cat nagare/server.pid) 2>/dev/null || true
            fi
          fi
          echo '--- Nagare server log ---'
          cat nagare/server.log || true

      - name: Comment SVG preview on PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Check if SVG file exists and is not empty
          if [ ! -f nagare-test.svg ]; then
            echo "SVG output missing" >&2
            exit 1
          fi

          if [ ! -s nagare-test.svg ]; then
            echo "SVG file is empty" >&2
            exit 1
          fi
          echo

          # Create temporary directory for the comment file
          mkdir -p tmp

          # Base64 encode the SVG
          SVG_BASE64=$(base64 -w 0 nagare-test.svg)

          # Generate the markdown comment with SVG as data URL
          {
            echo "### Nagare /test diagram preview"
            echo
            echo "<details>"
            echo "<summary>View diagram</summary>"
            echo
            echo "<img alt=\"Nagare /test preview\" src=\"data:image/svg+xml;base64,${SVG_BASE64}\" style=\"max-width: 800px; width: 100%; height: auto;\">"
            echo
            echo "</details>"
          } > tmp/comment.md

          # Post the comment
          gh pr comment "$PR_NUMBER" --body-file tmp/comment.md

      - name: Upload SVG artifact
        uses: actions/upload-artifact@v4
        with:
          name: nagare-test-preview
          path: nagare-test.svg
          if-no-files-found: error
