name: Render diagram preview

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: true
          cache-dependency-path: |
            nagare/go.mod
            nagare/go.sum

      - name: Download dependencies
        working-directory: nagare
        run: go mod download

      - name: Build Nagare server
        working-directory: nagare
        run: go build -o nagare-server ./cmd/nagare

      - name: Start Nagare server
        run: |
          cd nagare
          ./nagare-server > server.log 2>&1 &
          echo $! > server.pid

      - name: Fetch /test SVG output
        run: |
          for attempt in {1..60}; do
            if curl -fsS http://localhost:8080/test -o nagare-test.svg; then
              exit 0
            fi
            sleep 1
          done
          echo "Server failed to respond" >&2
          exit 1

      - name: Stop Nagare server
        if: always()
        run: |
          if [ -f nagare/server.pid ]; then
            kill $(cat nagare/server.pid) 2>/dev/null || true
            sleep 1
            if kill -0 $(cat nagare/server.pid) 2>/dev/null; then
              kill -9 $(cat nagare/server.pid) 2>/dev/null || true
            fi
          fi
          echo '--- Nagare server log ---'
          cat nagare/server.log || true

      - name: Validate SVG file
        run: |
          if [ ! -f nagare-test.svg ]; then
            echo "SVG output missing" >&2
            exit 1
          fi

          if [ ! -s nagare-test.svg ]; then
            echo "SVG file is empty" >&2
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to diagrams branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_SHA=$(gh pr view ${{ github.event.pull_request.number }} --json headRefOid -q .headRefOid)
          BRANCH_NAME="diagrams/pr-${{ github.event.pull_request.number }}-$PR_SHA"
          git checkout -b "$BRANCH_NAME"

          # Create diagrams directory if it doesn't exist
          mkdir -p .diagrams
          cp nagare-test.svg ".diagrams/pr-${{ github.event.pull_request.number }}.svg"

          git add .diagrams
          git commit -m "Add diagram for PR #${{ github.event.pull_request.number }}"
          git push origin "$BRANCH_NAME"

          # Save the URL for the next step
          echo "DIAGRAM_URL=https://raw.githubusercontent.com/${{ github.repository }}/$BRANCH_NAME/.diagrams/pr-${{ github.event.pull_request.number }}.svg" >> $GITHUB_ENV

      - name: Comment SVG preview on PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Create comment with the diagram
          echo "### Nagare /test diagram preview" > comment.md
          echo "" >> comment.md
          echo "<details>" >> comment.md
          echo "<summary>View diagram</summary>" >> comment.md
          echo "" >> comment.md
          echo "<img alt='Nagare /test preview' src='$DIAGRAM_URL' style='max-width: 100%; height: auto;'>" >> comment.md
          echo "" >> comment.md
          echo "</details>" >> comment.md

          # Post the comment
          gh pr comment "$PR_NUMBER" --body-file comment.md

          # Post the comment
          gh pr comment "$PR_NUMBER" --body-file comment.md
          echo "" >> comment.md
          echo "</details>" >> comment.md

          # Post the comment
          gh pr comment "$PR_NUMBER" --body-file comment.md
