name: Render diagram preview

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: true
          cache-dependency-path: |
            nagare/go.mod
            nagare/go.sum

      - name: Download dependencies
        working-directory: nagare
        run: go mod download

      - name: Build Nagare server
        working-directory: nagare
        run: go build -o nagare-server ./cmd/nagare

      - name: Start Nagare server
        run: |
          cd nagare
          ./nagare-server > server.log 2>&1 &
          echo $! > server.pid

      - name: Fetch /test SVG output
        run: |
          for attempt in {1..60}; do
            if curl -fsS http://localhost:8080/test -o nagare-test.svg; then
              exit 0
            fi
            sleep 1
          done
          echo "Server failed to respond" >&2
          exit 1

      - name: Stop Nagare server
        if: always()
        run: |
          if [ -f nagare/server.pid ]; then
            kill $(cat nagare/server.pid) 2>/dev/null || true
            sleep 1
            if kill -0 $(cat nagare/server.pid) 2>/dev/null; then
              kill -9 $(cat nagare/server.pid) 2>/dev/null || true
            fi
          fi
          echo '--- Nagare server log ---'
          cat nagare/server.log || true

      - name: Install librsvg
        run: sudo apt-get install -y librsvg2-bin

      - name: Convert SVG to PNG
        run: |
          if [ ! -f nagare-test.svg ]; then
            echo "SVG output missing" >&2
            exit 1
          fi

          if [ ! -s nagare-test.svg ]; then
            echo "SVG file is empty" >&2
            exit 1
          fi

          # Convert SVG to PNG with fixed dimensions
          rsvg-convert -w 1600 -h 800 nagare-test.svg > nagare-test.png

      - name: Upload diagram image
        uses: actions/upload-artifact@v4
        with:
          name: nagare-test-preview
          path: nagare-test.png
          if-no-files-found: error
          retention-days: 1

      - name: Comment PNG preview on PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # Create comment with the PNG link
          echo "### Nagare /test diagram preview" > comment.md
          echo "" >> comment.md
          echo "<details>" >> comment.md
          echo "<summary>View diagram</summary>" >> comment.md
          echo "" >> comment.md
          echo "![Nagare /test preview]($WORKFLOW_URL/artifacts/nagare-test-preview/nagare-test.png)" >> comment.md
          echo "" >> comment.md
          echo "</details>" >> comment.md

          # Post the comment
          gh pr comment "$PR_NUMBER" --body-file comment.md
          rsvg-convert -w 1600 -h 800 nagare-test.svg > nagare-test.png

      - name: Comment PNG preview on PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Base64 encode the PNG
          PNG_BASE64=$(base64 -w 0 nagare-test.png)

          # Create comment with the PNG embedded
          echo "### Nagare /test diagram preview" > comment.md
          echo "" >> comment.md
          echo "<details>" >> comment.md
          echo "<summary>View diagram</summary>" >> comment.md
          echo "" >> comment.md
          echo "<img alt='Nagare /test preview' src='data:image/png;base64,${PNG_BASE64}' style='max-width: 800px; width: 100%; height: auto;'>" >> comment.md
          echo "" >> comment.md
          echo "</details>" >> comment.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nagare-test-preview
          path: |
            nagare-test.svg
            nagare-test.png
          if-no-files-found: error
